// <auto-generated />

using System;
using System.Runtime.InteropServices;

namespace ManagedXZLZMA
{
    internal unsafe static class ManagedXZPInvoke
    {
        const string XamarinIOSObjectClassName = "Foundation.NSObject, Xamarin.iOS";

        public static readonly Delegates.lzma_code lzma_code;
        public static readonly Delegates.lzma_end lzma_end;
        public static readonly Delegates.lzma_auto_decoder lzma_auto_decoder;

        static ManagedXZPInvoke()
        {
            var isXamarinIOS = Type.GetType(XamarinIOSObjectClassName) != null;
            if (isXamarinIOS)
            {
                lzma_code = DllImportsXamarinIOS.lzma_code;
                lzma_end = DllImportsXamarinIOS.lzma_end;
                lzma_auto_decoder = DllImportsXamarinIOS.lzma_auto_decoder;
            }
            else
            {
                lzma_code = DllImports.lzma_code;
                lzma_end = DllImports.lzma_end;
                lzma_auto_decoder = DllImports.lzma_auto_decoder;
            }
        }

        public static class Delegates
        {
            public delegate lzma_ret lzma_code(lzma_stream* strm, lzma_action action);
            public delegate void lzma_end(lzma_stream* strm);
            public delegate lzma_ret lzma_auto_decoder(lzma_stream* strm, ulong memlimit, uint flags);
        }

        public class DllImports
        {
            private const string DllName = "libxzlzma";
            private const CallingConvention CallingConventionValue = CallingConvention.Cdecl;

            [DllImport(DllName, CallingConvention = CallingConventionValue)]
            public static extern lzma_ret lzma_code(lzma_stream* strm, lzma_action action);

            [DllImport(DllName, CallingConvention = CallingConventionValue)]
            public static extern void lzma_end(lzma_stream* strm);

            [DllImport(DllName, CallingConvention = CallingConventionValue)]
            public static extern lzma_ret lzma_auto_decoder(lzma_stream* strm, ulong memlimit, uint flags);
        }

        public class DllImportsXamarinIOS
        {
            private const string DllName = "__Internal";

            [DllImport(DllName)]
            public static extern lzma_ret lzma_code(lzma_stream* strm, lzma_action action);

            [DllImport(DllName)]
            public static extern void lzma_end(lzma_stream* strm);

            [DllImport(DllName)]
            public static extern lzma_ret lzma_auto_decoder(lzma_stream* strm, ulong memlimit, uint flags);
        }
    }
}