// <auto-generated />

using System;
using System.Runtime.InteropServices;

namespace ManagedXZLZMA
{
    internal enum lzma_ret
    {
        LZMA_OK = 0,
        LZMA_STREAM_END = 1,
        LZMA_NO_CHECK = 2,
        LZMA_UNSUPPORTED_CHECK = 3,
        LZMA_GET_CHECK = 4,
        LZMA_MEM_ERROR = 5,
        LZMA_MEMLIMIT_ERROR = 6,
        LZMA_FORMAT_ERROR = 7,
        LZMA_OPTIONS_ERROR = 8,
        LZMA_DATA_ERROR = 9,
        LZMA_BUF_ERROR = 10,
        LZMA_PROG_ERROR = 11,
    }

    internal enum lzma_action
    {
        LZMA_RUN = 0,
        LZMA_SYNC_FLUSH = 1,
        LZMA_FULL_FLUSH = 2,
        LZMA_FULL_BARRIER = 4,
        LZMA_FINISH = 3
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct lzma_stream
    {
        public IntPtr next_in;
        public UIntPtr avail_in;
        public UInt64 total_in;

        public IntPtr next_out;
        public UIntPtr avail_out;
        public UInt64 total_out;

        public IntPtr allocator;
        public IntPtr _internal;

        public IntPtr reserved_ptr1;
        public IntPtr reserved_ptr2;
        public IntPtr reserved_ptr3;
        public IntPtr reserved_ptr4;
        public UInt64 reserved_int1;
        public UInt64 reserved_int2;
        public UIntPtr reserved_int3;
        public UIntPtr reserved_int4;
        public uint reserved_enum1;
        public uint reserved_enum2;
    }
}